# Generated by Django 5.2.7 on 2025-11-01 16:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CitaBibliografica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.PositiveIntegerField(unique=True)),
                ('cita_completa', models.TextField(help_text='Cita bibliográfica completa')),
                ('enlace', models.URLField(blank=True, max_length=500)),
                ('tipo_recurso', models.CharField(blank=True, max_length=100)),
                ('autores', models.CharField(blank=True, max_length=300)),
                ('año_publicacion', models.PositiveIntegerField(blank=True, null=True)),
                ('revista_editorial', models.CharField(blank=True, max_length=200)),
            ],
            options={
                'verbose_name': 'Cita Bibliográfica',
                'verbose_name_plural': 'Citas Bibliográficas',
                'ordering': ['numero'],
            },
        ),
        migrations.CreateModel(
            name='Concepto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.PositiveIntegerField()),
                ('subtema', models.CharField(max_length=300)),
                ('descripcion', models.TextField()),
                ('orden', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Concepto',
                'verbose_name_plural': 'Conceptos',
                'ordering': ['seccion', 'orden'],
            },
        ),
        migrations.CreateModel(
            name='Seccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('descripcion', models.TextField(blank=True)),
                ('orden', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Sección',
                'verbose_name_plural': 'Secciones',
                'ordering': ['orden'],
            },
        ),
        migrations.CreateModel(
            name='Referencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cita', models.TextField(help_text='Formato completo de la cita bibliográfica')),
                ('enlace', models.URLField(blank=True, max_length=500)),
                ('tipo', models.CharField(choices=[('libro', 'Libro'), ('articulo', 'Artículo'), ('sitio_web', 'Sitio Web'), ('video', 'Video'), ('otro', 'Otro')], default='articulo', max_length=20)),
                ('autores', models.CharField(blank=True, max_length=300)),
                ('año', models.PositiveIntegerField(blank=True, null=True)),
                ('concepto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='referencias', to='API.concepto')),
            ],
            options={
                'verbose_name': 'Referencia',
                'verbose_name_plural': 'Referencias',
            },
        ),
        migrations.AddField(
            model_name='concepto',
            name='seccion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conceptos', to='API.seccion'),
        ),
        migrations.AlterUniqueTogether(
            name='concepto',
            unique_together={('seccion', 'numero')},
        ),
    ]
